#!/usr/bin/env python3

import os
import sys
import asyncio


sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../../..'))
from starkware.starknet.cli.starknet_cli import main  # noqa

if __name__ == '__main__':
    sys.exit(asyncio.run(main()))
