#!/usr/bin/env python3.7

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../../../..'))
from starkware.cairo.lang.compiler.cairo_format import main  # noqa

if __name__ == '__main__':
    sys.exit(main())
