load("//bazel_utils:solidity.bzl", "sol_library")

sol_library(
    name = "named_storage_sol",
    srcs = [
        "NamedStorage.sol",
    ],
    visibility = ["//visibility:public"],
    deps = [],
)

sol_library(
    name = "common_library_sol",
    srcs = [
        "Addresses.sol",
    ],
    visibility = ["//visibility:public"],
    deps = [],
)
