py_binary(
    name = "fixed_cairo_compile",
    srcs = ["fixed_cairo_compile.py"],
    data = ["fixed_cairo_compile.sh"],
    main = "fixed_cairo_compile.py",
    visibility = ["//visibility:public"],
)
