CAIRO_LANG_VENV_ADDITIONAL_LIBS = []
CAIRO_VM_CRYPTO_ADDITIONAL_LIBS = []
CAIRO_COMMON_LIB_ADDITIONAL_FILES = []
CAIRO_COMMON_LIB_ADDITIONAL_LIBS = []
CAIRO_INSTANCES_LIB_ADDITIONAL_FILES = []
CAIRO_COMPILER_ARCHIVE = "sierra-compiler-major-1"
