load("//src/starkware/cairo/lang:cairo_rules.bzl", "cairo_library")

package(default_visibility = ["//visibility:public"])

cairo_library(
    name = "cairo_secp256r1",
    srcs = [
        "bigint.cairo",
        "constants.cairo",
        "ec.cairo",
        "field.cairo",
    ],
    visibility = ["//visibility:public"],
)
