load(":layouts_gen.bzl", "generate_layouts_libs")

layouts = [
    "all_cairo",
    "dex",
    "dynamic",
    "recursive",
    "small",
    "starknet",
    "starknet_with_keccak",
]

generate_layouts_libs(layouts)
