def generate_layouts_libs(layouts):
    for layout in layouts:
        native.py_library(
            name = "starkware_cairo_stark_verifier_air_{}_lib".format(layout),
            srcs = [
            ],
            data = [
                "//src/starkware/cairo/stark_verifier/air/layouts/{}:autogenerated.cairo".format(layout),
                "//src/starkware/cairo/stark_verifier/air/layouts/{}:composition.cairo".format(layout),
                "//src/starkware/cairo/stark_verifier/air/layouts/{}:global_values.cairo".format(layout),
                "//src/starkware/cairo/stark_verifier/air/layouts/{}:periodic_columns.cairo".format(layout),
                "//src/starkware/cairo/stark_verifier/air/layouts/{}:public_verify.cairo".format(layout),
                "//src/starkware/cairo/stark_verifier/air/layouts/{}:verify.cairo".format(layout),
                "//src/starkware/cairo/stark_verifier/core:stark",
            ],
            tags = [
                "external_cairo",
                "external_cairo-docs",
            ],
            visibility = ["//visibility:public"],
        )
