from starkware.crypto.signature.signature import FIELD_PRIME

STARKNET_LANG_DIRECTIVE = 'starknet'

FIELD_SIZE = FIELD_PRIME

CALL_DATA_ELEMENT_LOWER_BOUND = 0
CALL_DATA_ELEMENT_UPPER_BOUND = FIELD_SIZE
CONTRACT_ADDRESS_BITS = 251
CONTRACT_ADDRESS_LOWER_BOUND = 0
CONTRACT_ADDRESS_UPPER_BOUND = 2**CONTRACT_ADDRESS_BITS
CONTRACT_STATES_MERKLE_TREE_HEIGHT = 251
ENTRY_POINT_OFFSET_LOWER_BOUND = 0
ENTRY_POINT_OFFSET_UPPER_BOUND = FIELD_SIZE
ENTRY_POINT_SELECTOR_LOWER_BOUND = 0
ENTRY_POINT_SELECTOR_UPPER_BOUND = FIELD_SIZE
